// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBDqyQ6I_xXe-HoOC0v6gABhwI7UwGwYY',
    appId: '1:1000743611486:web:9bc7b81d16ac88867bd8cf',
    messagingSenderId: '1000743611486',
    projectId: 'traveladviser-ed028',
    authDomain: 'traveladviser-ed028.firebaseapp.com',
    storageBucket: 'traveladviser-ed028.appspot.com',
    measurementId: 'G-8KFKPYBLFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD27hX13F8A7tvh9w_MKpLhd7C5kyqOuh8',
    appId: '1:1000743611486:android:896725d3673f63697bd8cf',
    messagingSenderId: '1000743611486',
    projectId: 'traveladviser-ed028',
    storageBucket: 'traveladviser-ed028.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx2OaZw8kDsQSWwgzJYggmzjUZFZdT8LQ',
    appId: '1:1000743611486:ios:b05f3789e80da3947bd8cf',
    messagingSenderId: '1000743611486',
    projectId: 'traveladviser-ed028',
    storageBucket: 'traveladviser-ed028.appspot.com',
    iosClientId: '1000743611486-oaarlcg3j9l2lcoqeba316q5nobupq9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripAdviser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx2OaZw8kDsQSWwgzJYggmzjUZFZdT8LQ',
    appId: '1:1000743611486:ios:b05f3789e80da3947bd8cf',
    messagingSenderId: '1000743611486',
    projectId: 'traveladviser-ed028',
    storageBucket: 'traveladviser-ed028.appspot.com',
    iosClientId: '1000743611486-oaarlcg3j9l2lcoqeba316q5nobupq9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripAdviser',
  );
}
